name: moonshot option test
description: "Test the moonshot option"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        - uses: oven-sh/setup-bun@v1
        - name: Use Cached Dependencies
          uses: actions/cache@v4
          with:
              path: "**/dist"
              key: ${{ runner.os }}-build-${{ github.sha }}
        - name: Run cli
          uses: ./.github/actions/helper/run-cli
          with:
              moonshot: "true"
              small: "true"
        - name: check workflow exists
          uses: ./.github/actions/helper/exist-file
          with:
              path: test/.github/workflows/ci.yml
