name: "Run Package Scripts"
description: "Run all scripts defined in package.json"
inputs:
    path:
        description: "The path to the directory containing the package.json file"
        required: true
        default: "."

runs:
    using: "composite"
    steps:
        - name: set-node
          uses: actions/setup-node@v2
          with:
              node-version: "20.x"
        - name: check all scripts are executable
          uses: actions/github-script@v6
          with:
              script: |
                  const fs = require("fs");
                  const { exec:nodeExec } = require("child_process");
                  const path = require("path");
                  const packageJsonPath = "${{inputs.path}}/package.json";
                  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath));
                  const scripts = packageJson.scripts;

                  Object.keys(scripts).filter((script)=>script!="start").forEach((script) => {
                      nodeExec(`npm run ${script}`, { cwd: path.resolve("${{inputs.path}}") }, (err, stdout, stderr) => {
                          if (err) {
                              console.error(`Error executing script ${script}: ${err}`);
                              process.exit(1);
                          }
                          console.log(`Output for script ${script}: ${stdout}`);
                      });
                  });
                  if(Object.keys(scripts).includes("start")){
                      nodeExec(`npm run start`, { cwd: path.resolve("${{inputs.path}}") }, (err, stdout, stderr) => {
                          if (err) {
                              console.error(`Error executing script start: ${err}`);
                              process.exit(1);
                          }
                          console.log(`Output for script start: ${stdout}`);
                      });
                  }
