name: "Run Package Scripts"
description: "Run all scripts defined in package.json"
inputs:
    path:
        description: "The path to the directory containing the package.json file"
        required: true
        default: "."

runs:
    using: "composite"
    steps:
        - name: check all scripts are executable
          uses: actions/github-script@v6
          with:
              require:
              script: |
                  const fs = require("fs");
                  const { exec } = require("child_process");

                  const packageJsonPath = "${{inputs.path}}/package.json";
                  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath));
                  const scripts = packageJson.scripts;

                  Object.keys(scripts).forEach((script) => {
                      exec(`npm run ${script}`, { cwd: path }, (err, stdout, stderr) => {
                          if (err) {
                              console.error(`Error executing script ${script}: ${err}`);
                              process.exit(1);
                          }
                          console.log(`Output for script ${script}: ${stdout}`);
                      });
                  });
