name: recommend option test
description: "Test the recommend option"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        - uses: pnpm/action-setup@v2.2.2
          with:
              version: 7.1.0

        - name: Use Cached Dependencies

          uses: actions/cache@v4
          with:
              path: "**/dist"
              key: ${{ runner.os }}-build-${{ github.sha }}
        - name: Run cli
          uses: ./.github/actions/helper/run-cli
          with:
              recommend: "true"
              small: "true"
              eslint: "true"
        - name: check workflow exists
          uses: ./.github/actions/helper/exist-file
          with:
              path: .eslintrc.json
