name: recommend option test
description: "Test the recommend option"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        - name: Use Cached Dependencies
          uses: actions/cache@v4
          with:
              path: "**/dist"
              key: ${{ runner.os }}-build-${{ github.sha }}
        - name: Run cli
          run: |
              npx create-template-next
          shell: bash
        - name: check workflow exists
          uses: ./.github/actions/helper/exist-file
          with:
              path: .github/workflows/ci.yml
