name: check file exists
description: "Check if a file exists"
inputs:
    path:
        description: "Path to file"
        required: true
runs:
    using: "composite"
    steps:
        - name: Check if file exists
          run: |
              if [ -f ${{ inputs.path }} ]; then
                echo "File exists"
              else
                echo "File does not exist"
                exit 1
              fi
          shell: bash
