on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: check recommend
              uses: ./.github/actions/test-recommend
            - name: check moonshot
              uses: ./.github/actions/test-moonshot
            - name: check fail
              uses: ./.github/actions/fail
